digi\eslTools\Entities\Backoffice:
  type: entity
  table: backoffice
  id:
    id:
      type: integer
      generator: 
        strategy: AUTO

  oneToMany:
    stores:
      targetEntity: Store
      mappedBy: backoffice

  fields:
    backofficename:
      type: string
      length: 45