Digitools\Todo\Entities\Todo:
  type: entity  
  table: todo  
  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  oneToOne:
    priority:
      targetEntity: Priority
      joinColumn:
        name: priorityid
        referencedColumnName: id

  fields:
    title:
      type: string
      length: 255

    finishstate:
      type: integer

    creationdate:
      type: datetime

    tododate:
      type: datetime

    finishdate:
      type: datetime
