digi\eslTools\Entities\Store:
  type: entity
  repositoryClass: digi\eslTools\Entities\Repo\StoreRepo
  table: store
  id:
    id:
      type: integer
      generator: 
        strategy: AUTO

  manyToOne:
    storegroup:
      targetEntity: Storegroup
      inversedBy: stores
      joinColumn:
        name: storegroup_id
        referencedColumnName: id

    backoffice:
      targetEntity: Backoffice
      inversedBy: stores
      joinColumn: 
        name: backoffice_id
        referencedColumnName: id

    postcode:
      targetEntity: Postcode
      inversedBy: stores
      joinColumn: 
        name: postcode_id
        referencedColumnName: id

    contract:
      targetEntity: Contract
      inversedBy: stores
      joinColumn:
        name: contract_id
        referencedColumnName: id

    contracttype:
      targetEntity: Contracttype
      inversedBy: stores
      joinColumn:
        name: contract_type_id
        referencedColumnName: id

  fields:
    storename:
      type: string
      length: 65
    synergie:
      type: string
      length: 45
    ip:
      type: string
      length: 64
    softwareversion:
      type: string
      length: 256
    contact:
      type: string
      length: 256
    email:
      type: string
      length: 65
    picurl:
      type: string
      length: 255