Digitools\Logbook\Entities\Logfile:
  type: entity
  repositoryClass: Digitools\Logbook\Entities\Repo\LogfileRepo
  table: log_file
  id:
    id:
      type: integer
      generator: 
        strategy: AUTO
      
  manyToOne:
    log:
      targetEntity: Digitools\Logbook\Entities\Log
      inversedBy: logfiles
      joinColumn:
        name: log_id
        referencedColumnName: id
        
  fields:
    path:
      type: string
      nullable: false
      length: 255
      
    filename:
      type: string
      nullable: false
      length: 255