digi\eslTools\Entities\Contract:  
  type: entity
  table: contract
  id:
    id:
      type: integer
      generator: 
        strategy: AUTO

  oneToMany:
    stores:
      targetEntity: Store
      mappedBy: contract

  fields:
    company:
      type: string
      length: 45