Digitools\Logbook\Entities\Log:
  type: entity
  //repositoryClass: Digitools\Logbook\Entities\Repo\UserRepo
  table: digi_log  
  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  manyToOne:
    user:
      targetEntity: User 
      joinColumn:
        name: user_id
        referencedColumnName: id
        
  manyToMany:
    tags:
      targetEntity: Tag
      inversedBy: logs
      joinTable:
        name: log_tags
        joinColumns:
          log_id:
            referencedColumnName: id
        inverseJoinColumns:
          tag_id:
            referencedColumnName: id

  fields:
    created:
      type: datetime      
      nullable: false    
