Digitools\Logbook\Entities\Log:
  type: entity
  repositoryClass: Digitools\Logbook\Entities\Repo\LogRepo
  table: log  
  id:
    id:
      type: integer
      generator:
        strategy: AUTO

  manyToOne:
    user:
      targetEntity: Digitools\EslTools\Entities\User
      joinColumn:
        name: user_id
        referencedColumnName: id
        
  manyToMany:
    tags:
      targetEntity: Tag
      inversedBy: logs
      joinTable:
        name: log_tags
        joinColumns:
          log_id:
            referencedColumnName: id
        inverseJoinColumns:
          tag_id:
            referencedColumnName: id

  fields:
    created:
      type: datetime      
      nullable: false

    entry:
      type: text
      nullable: false
