digi\eslTools\Entities\Contracttype:  
  type: entity
  table: contract_type
  id:
    id:
      type: integer
      generator: 
        strategy: AUTO

  oneToMany:
    stores:
      targetEntity: Store
      mappedBy: contracttype

  fields:
    typename:
      type: string
      length: 45